server:
  port: 7777
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7770/eureka/

management:
  security:
    enabled: false

logging:
  level:
    root: INFO

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true

zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    usercenter:
      path: /usercenter/**
      serviceId: irvin-uc-server
      retryable: true