# server
server:
  port: 7000

# spring
spring:
  application:
    name: irvin-uc-server
  datasource:
      url: jdbc:mysql://localhost:3306/irvin?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  # redis
  redis:
    host: localhost
    database: 7
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1000
# logger
logging:
  level:
   root: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/ # 服务注册中心地址


