# server
server:
  port: 7777

# spring
spring:
  application:
    name: irvin-uc-server
  # redis
  redis:
    host: localhost
    database: 7
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1000
# logger
logging:
  level: debug



